Pp 30 create header and navbar
Code-the-Dream-School/ffprac-team6 pull request #14
Opened 2024-03-16 18:04 UTC by Victoria240

Not sure if there are any other links we need to include in the navbar, but I tried to follow what we had in the design mocks
 I've also incorporated the login and signup feature

2024-03-17 05:16 UTC, AnnaPestova1 commented on lib/mongo/dbConnect.js
> +  // try {
please remove commented lines.

2024-03-17 05:24 UTC, AnnaPestova1 requested changes
Hi Victoria! You did a great job! Your header looks nice!
I mentioned couple issues:
1. seems you didn't connected MongoDB on your side. Follow this instruction https://docs.google.com/document/d/12ol8Vwz4sGetn3YBDVqjiInk9u6008QfmLFmAtTlxAs/edit?usp=sharing and, please, comment out all lines you changed in dbConnect.js file.
2. Our team decided use MUI as our styling system. Could you please change you code according MUI documentation (https://mui.com/material-ui/getting-started/).
Thank you!

2024-03-19 17:09 UTC, AnnaSolovykh requested changes
Nice work! The only thing is that when a person is logged in, the "log in" link in the navbar should turn to "log out". This feature is in AuthControl component, you need to import it nicely into Navbar and style accordingly. In AuthControl there is mainly the logic, not styled. <img width="1724" alt="Screenshot 2024-03-19 at 13 04 01" src="https://github.com/Code-the-Dream-School/ffprac-team6/assets/114008959/32527079-fc01-4aa2-83c6-9f2b16adce8e">  <img width="1205" alt="Screenshot 2024-03-19 at 13 09 13" src="https://github.com/Code-the-Dream-School/ffprac-team6/assets/114008959/229cfae6-41bd-4246-8faf-ff71f1afc995">

2024-03-20 05:43 UTC, AnnaPestova1 requested changes
Hi Victoria! the navbar looks great! could you please solve errors in console? 
<img width="574" alt="image" src="https://github.com/Code-the-Dream-School/ffprac-team6/assets/106414157/ab8cca4b-43c5-4b61-bfb3-5cb1d52e45bc">

maybe this example will help you to figure out how to solve warnings: https://mui.com/material-ui/react-app-bar/

2024-03-26 23:57 UTC, AnnaSolovykh approved these changes

2024-03-26 23:57 UTC, AnnaPestova1 approved these changes

2024-03-27 17:31 UTC, merged