Pp66 cards home page
Code-the-Dream-School/ffprac-team6 pull request #33
Opened 2024-03-28 17:15 UTC by ofeterovskaya

1. Add cards components to the home page
2. Add a new folder cards to the public folder
3. Add imgs into the card folder

2024-03-28 17:19 UTC, ofeterovskaya commented
ops, I just realized I forgot to add  links to the filtered market page. I''ll do it later today

2024-03-29 00:43 UTC, AnnaPestova1 requested changes
Oksana! Great job! 
one small issue: according our model 
<img width="640" alt="image" src="https://github.com/Code-the-Dream-School/ffprac-team6/assets/106414157/a582a704-ef56-472b-aa2b-70322bb39340">
there is category "Sport Card", not "Sport Card**s**" The same issue with the "Yu-Gi-Oh" name. Could you please fix this typos?

2024-03-29 00:43 UTC, AnnaPestova1 commented on components/CardsHome.jsx
> +  useEffect(() => {
do we need this useEffect here?

2024-03-29 02:31 UTC, ofeterovskaya commented on components/CardsHome.jsx
> +  useEffect(() => {
fixed and did new commit

2024-03-29 14:23 UTC, ofeterovskaya commented on components/CardsHome.jsx
> +  useEffect(() => {
Yu-Gi-Oh! now is on

2024-03-30 17:40 UTC, AnnaPestova1 approved these changes

2024-03-31 16:05 UTC, AnnaSolovykh approved these changes

2024-04-01 02:38 UTC, merged