PP-68-items-I-sell
Code-the-Dream-School/ffprac-team6 pull request #35
Opened 2024-03-31 02:17 UTC by Victoria240

The data on this page has been hard-coded for now. I'll update the component when the API/route has been set up.

2024-03-31 20:03 UTC, AnnaPestova1 requested changes
Hi Victoria! I like how your page looks. There are some issues:  this part 
<img width="1180" alt="image" src="https://github.com/Code-the-Dream-School/ffprac-team6/assets/106414157/3c76e1cb-d3c2-4fdf-8998-ca2a4aedff21">
is from the user profile page. On the profile page, our user will see all information about himself. As a seller too. We do not need this pars here.

But on this page user should be able to add a new card (we have API for it),  edit a card and delete a card (edit and delete functionality is already in our API. We will have API to GET seller's cards in my next pull request. 

This 
<img width="491" alt="image" src="https://github.com/Code-the-Dream-School/ffprac-team6/assets/106414157/4c57aaf5-57dc-45a6-8691-7123065035fd">
 will be on the Profile page too. 

the add new card button doesn't have any margins:

<img width="209" alt="image" src="https://github.com/Code-the-Dream-School/ffprac-team6/assets/106414157/b3841602-723a-4284-bed5-26859231e706">


Maybe you should look at the Container component https://mui.com/material-ui/react-container/. It will help you with the layout. 

if we add sold items, we also need to add available items.
<img width="251" alt="image" src="https://github.com/Code-the-Dream-School/ffprac-team6/assets/106414157/ab73a70b-2379-4673-8594-20de05284e46">

I think the purpose of this page - is to allow user to see his cards, add, edit and delete them

2024-03-31 20:03 UTC, AnnaPestova1 commented on app/seller-items/page.js
> +"use client";
Hi! we have a route for this page 
<img width="265" alt="image" src="https://github.com/Code-the-Dream-School/ffprac-team6/assets/106414157/de2f4ed4-5e5d-4389-94e0-c62387e80055">
/sell

2024-03-31 20:03 UTC, AnnaPestova1 commented on app/seller-items/page.js
> +                        <Grid item xs={12} sm={6} md={4} lg={3} key={item.id}>
What do you think if we will reduce the air between cards? Right now with current card sizes, I have a large gap between cards on the medium size screen 
<img width="1151" alt="image" src="https://github.com/Code-the-Dream-School/ffprac-team6/assets/106414157/df09af6b-801a-43a4-ae67-08e226c8b338">
and on the small size screen too 
<img width="543" alt="image" src="https://github.com/Code-the-Dream-School/ffprac-team6/assets/106414157/902c3eef-08e0-47b9-91ba-2d025b36b0dd">


 (I am not sure about this part)

2024-03-31 21:42 UTC, AnnaPestova1 requested changes

2024-03-31 21:42 UTC, AnnaPestova1 commented on app/market/item/[id]/page.jsx
> +            <Card style={{ boxShadow: 'none', marginRight: theme.spacing(2) }}>
we should use 
our CardComponent. its height will be fixed in the Luba's pull request.

2024-04-05 00:06 UTC, AnnaPestova1 approved these changes
Great job, Victoria!

2024-04-05 16:22 UTC, AnnaSolovykh approved these changes

2024-04-06 21:37 UTC, merged