Pp 69 refactoring footer
Code-the-Dream-School/ffprac-team6 pull request #36
Opened 2024-03-31 04:03 UTC by LiubovCass

Refactoring Footer with MUI components and Next js Link

2024-03-31 20:25 UTC, AnnaPestova1 requested changes

2024-03-31 20:25 UTC, AnnaPestova1 commented on components/Footer.jsx
> +        <Link href="/team" style={{ textDecoration: "none", color: "background.paper" }}>
Hi Luba! Thank you for MUI in our component.

Link here is not MUI component, so it doesn't see our theme such easy in styles. I mention that this code you are added before, disappeared from out global.css:
`a,
a:link,
a:visited,
a:focus,
a:hover,
a:active {
  color: #FFFFFF;
  text-decoration: none;
  cursor: crosshair;
}
`
we need to fix this part: 
<img width="342" alt="image" src="https://github.com/Code-the-Dream-School/ffprac-team6/assets/106414157/c2a9cc38-242a-42ed-89fb-e66741329ff6">

2024-04-02 03:48 UTC, AnnaPestova1 approved these changes

2024-04-03 06:18 UTC, ofeterovskaya approved these changes
Looks good

2024-04-03 22:26 UTC, merged